export const path = {
  home: '/',
  payment: '/transaction/payment',
  login: '/auth/login',
  register: '/auth/register',
  registerSuccess: '/auth/register-success',
  verify: '/auth/email-verification',
  forgot: '/auth/forgotten-password',
  reset: '/auth/reset-password',
  dashboard: '/dashboard',
  success: '/transaction/success',
  cancelled: '/transaction/cancelled',
  failure: '/transaction/failure',
  redirecting: '/transaction/redirecting',
};
